# Generated by Django 2.1.4 on 2019-01-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190109_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default='', help_text='Enter a brief description of the book', max_length=1000),
            preserve_default=False,
        ),
    ]
